# -*- coding: utf-8 -*-
"""Route B: rewrite manuscript template sections 3.4, Table 6 title, Methods 2.7, Limitations."""
import io
from pathlib import Path

P = Path(r"D:\TT paper\Path-AGNN-Cox Pathway-Constrained Adaptive Graph Neural Network for Interpretable Survival Analysis") / "manuscript" / "Path-AGNN-Cox_manuscript_template.md"
t = io.open(P, encoding="utf-8-sig").read()

def rep(old, new):
    global t
    n = t.count(old)
    assert n == 1, f"expected 1 occurrence, found {n}: {old[:80]!r}"
    t = t.replace(old, new)

# A1 header paragraph
rep(
"A central claim of this work is that the sample-specific edge weights are not purely mathematical artifacts but carry patient-specific variation that we test for biological content. We therefore extracted, for every patient, the last-layer adaptive attention weights within each pathway block and compared high- vs. low-risk strata (median risk split) in LUAD ({{FREF:REWIRING}}; BRCA in {{FREF:REWIRING|E}}).",
"A central claim of this work is that the sample-specific edge weights carry patient-specific variation that can be tested formally for biological content. We therefore extracted, for every patient, the last-layer adaptive attention weights within each pathway block and compared high- vs. low-risk strata (median risk split) in LUAD and BRCA ({{FREF:REWIRING}})."
)

# A2 figure caption
rep(
"- **{{FDEF:REWIRING}}. Patient-specific pathway rewiring.** (A) Top rewired pathways ranked by the standardized between-stratum statistic |z| (LUAD). (B) Mean within-pathway edge weight by risk stratum for the top-5 pathways (LUAD). (C) Label-permutation null distribution: observed number of significantly rewired pathways (FDR q<0.05) versus the permutation null mean and maximum (1,000 permutations; LUAD and BRCA). (D) Correlation between per-patient rewiring magnitude and clinical malignancy indicators (LUAD). (E) Top rewired pathways (BRCA).",
"- **{{FDEF:REWIRING}}. Patient-specific pathway rewiring.** (A) Between-stratum effect sizes (Cohen's d with 95% CI) for all {{PERM_N_PATHWAYS}} pathways in LUAD, with the two pathways surviving per-pathway label permutation and BH-FDR correction highlighted. (B) Same as A for BRCA. (C) Cohort-level label-permutation null: number of significant pathways observed versus the null mean and maximum under 1,000 label permutations (LUAD and BRCA). (D) Correlation between per-patient rewiring magnitude and clinical malignancy indicators (LUAD). (E) Matched random gene-set controls: distribution of the null percentiles of real pathways for the edge-matched and density-matched nulls in LUAD and BRCA, with the 50th percentile (chance) marked."
)

# A3 3.4.1
rep(
"**3.4.1. Rewiring is not a label artifact.** The per-sample mean edge weight within each pathway was compared between high- and low-risk strata (median risk split). In BRCA, {{PERM_BRCA_SIG}} of {{PERM_N_PATHWAYS}} pathways showed significant between-stratum differences (BH-FDR q<0.05); in LUAD, {{PERM_LUAD_SIG}} pathways did. To exclude the possibility that these differences merely reflect the risk stratification used to define the strata, we repeated the pathway-level tests under 1,000 label permutations: the null distribution yielded a mean of {{PERM_LUAD_NULL_MEAN}} significant pathways in LUAD and {{PERM_BRCA_NULL_MEAN}} in BRCA (maximum {{PERM_LUAD_NULL_MAX}} in LUAD and {{PERM_BRCA_NULL_MAX}} in BRCA), versus {{PERM_BRCA_SIG}} and {{PERM_LUAD_SIG}} observed (permutation {{PERM_BRCA_P}} and {{PERM_LUAD_P}}; {{TREF:REWIRING}}); the BRCA permutation P equals the resolution limit of the 1,000-permutation null (minimum attainable P = 1/1001), with the observed count of 43 far exceeding the null maximum of 19. The top-ranked rewired pathways in both cancers are qualitatively coherent with tumor progression biology (e.g., cell cycle, DNA replication, homologous recombination, apoptosis and HIF-1 signaling in BRCA; {{TOP_REWIRED_PATHWAYS}} in LUAD).",
"**3.4.1. Between-stratum rewiring exceeds label-permutation chance but is not globally pathway-selective.** The per-sample mean edge weight within each pathway was compared between high- and low-risk strata (median risk split) with Cohen's d and 95% CI ({{FREF:REWIRING}}A,B). After per-pathway label permutation (1,000 permutations) and BH-FDR correction, {{PWP_BRCA_SIG}} of {{PERM_N_PATHWAYS}} pathways in BRCA and {{PWP_LUAD_SIG}} in LUAD remained significant; the two LUAD pathways were Homologous recombination (d = {{D_LUAD_HR}}, 95% CI {{D_LUAD_HR_CI}}) and DNA replication (d = {{D_LUAD_DNA}}, 95% CI {{D_LUAD_DNA_CI}}) ({{TREF:REWIRING}}). At the cohort level, the number of pathways with BH-FDR q<0.05 on the pathway-level test exceeded the 1,000-permutation label-permutation null in both cancers (LUAD: {{PERM_LUAD_SIG}} observed vs. null mean {{PERM_LUAD_NULL_MEAN}}, maximum {{PERM_LUAD_NULL_MAX}}, permutation {{PERM_LUAD_P}}; BRCA: {{PERM_BRCA_SIG}} observed vs. null mean {{PERM_BRCA_NULL_MEAN}}, maximum {{PERM_BRCA_NULL_MAX}}, permutation {{PERM_BRCA_P}}, the resolution limit of the 1,000-permutation null). The between-stratum differences therefore reflect risk-associated structure in the attention weights rather than the risk stratification itself.\n\nPathway identity, however, was not globally selective. Under matched random gene-set controls preserving gene-set size and either internal edge count or graph density, the real pathways were not enriched above the matched nulls: the median percentile of the real pathways was {{MATCHED_LUAD_MED}} in LUAD, with {{MATCHED_LUAD_EXCEED}} of 53 pathways above the 95th percentile (expected {{MATCHED_EXPECTED}}), and {{MATCHED_BRCA_MED}} in BRCA, with {{MATCHED_BRCA_EXCEED}} of 53 (expected {{MATCHED_EXPECTED}}); the density-matched control gave median percentiles of {{MATCHED_BLOCK_LUAD_MED}} and {{MATCHED_BLOCK_BRCA_MED}}, respectively. Known-pathway enrichment of the top-20 pathways ranked by permutation P was not significant in LUAD ({{ENRICH_LUAD_HITS}} hits, {{ENRICH_LUAD_P}}). The two LUAD pathways that survived the permutation-calibrated test exceeded 94%–96% of the density-matched null sets, and the MAPK signaling pathway in BRCA exceeded all 200 matched sets (d = {{D_BRCA_MAPK}}, 95% CI {{D_BRCA_MAPK_CI}}); these observations are hypothesis-generating rather than evidence of global pathway-specific rewiring. The pathway partition therefore supplies interpretable labels for the rewiring output, but canonical pathway identity is not statistically required to produce it."
)

# A4 3.4.2
rep(
"**3.4.2. Static models cannot produce rewiring; the pathway prior is an interpretive labeling rather than a statistical necessity.** As a negative control, the static pathway GNN (−Adaptive) was subjected to the identical analysis; its total edge-weight variance across patients was {{STATIC_NULL_VAR}}—essentially zero by construction—whereas the adaptive model produced a total edge-weight variance of {{ADAPTIVE_REWIRE_VAR}}—orders of magnitude larger—indicating that the between-stratum differences of Section 3.4.1 are attributable to the sample-specific attention mechanism rather than to the fixed adjacency. We also retrained the adaptive model with randomized pathway partitions (block sizes preserved; three seeds). Random partitions yielded 26−48 significantly rewired pathways, i.e., between-stratum attention differences are not unique to canonical pathway structure; the pathway partition supplies biologically interpretable labels for these differences rather than being statistically necessary.",
"**3.4.2. Static models cannot produce rewiring.** As a negative control, the static pathway GNN (−Adaptive) was subjected to the identical analysis; its total edge-weight variance across patients was {{STATIC_NULL_VAR}}, essentially zero by construction, whereas the adaptive model produced a total edge-weight variance of {{ADAPTIVE_REWIRE_VAR}}, orders of magnitude larger; the between-stratum differences of Section 3.4.1 are therefore attributable to the sample-specific attention mechanism rather than to the fixed adjacency. Retraining the adaptive model with randomized pathway partitions (block sizes preserved; three seeds) yielded 26–48 significant pathways, consistent with the matched gene-set controls of Section 3.4.1: between-stratum attention differences are not unique to canonical pathway structure, and the pathway partition supplies biologically interpretable labels rather than being statistically necessary."
)

# A5 3.4.4 comparison sentence
rep(
"compared with 43 of 53 and 3 of 53 for the adaptive pathway-constrained model ({{TREF:REWIRING}}); the pathway-constrained model yielded substantially more detectable between-stratum differences, indicating that the pathway partition contributes to the statistical detection of these differences; consistent with the randomized-partition control (Section 3.4.1), canonical pathway structure is nonetheless not uniquely required to produce them.",
"compared with {{PWP_BRCA_SIG}} of 53 and {{PWP_LUAD_SIG}} of 53 for the adaptive pathway-constrained model under the same permutation-calibrated procedure ({{TREF:REWIRING}}); the pathway-constrained model yielded more detectable between-stratum differences in BRCA and a comparable count in LUAD, indicating that the pathway partition contributes to the statistical detection of these differences; consistent with the randomized-partition control (Section 3.4.2), canonical pathway structure is nonetheless not uniquely required to produce them."
)

# A6 limitations third + fourth
rep(
"Third, hypergeometric enrichment of the top-20 rewired pathways against a curated LUAD driver-pathway list was not significant with P=0.875; an equivalent test was not performed for BRCA because no matched curated driver-pathway list was available, and enrichment should not be over-interpreted.",
"Third, hypergeometric enrichment of the top-20 rewired pathways ranked by permutation P against a curated LUAD driver-pathway list was not significant ({{ENRICH_LUAD_HITS}} hits, {{ENRICH_LUAD_P}}); an equivalent test was not performed for BRCA because no matched curated driver-pathway list was available."
)
rep(
"Fourth, randomized pathway partitions produced comparable or larger numbers of between-stratum significant pathways, indicating that between-stratum attention differences are generic; the pathway prior supplies biological context for interpreting them.",
"Fourth, matched random gene-set controls did not show global selectivity of canonical pathway identity for the between-stratum differences, and the few pathways that exceeded both permutation and matched-set nulls remain hypothesis-generating; the pathway prior is retained as an interpretable organizing principle rather than as evidence of specific pathway activation."
)

# A7 table title
rep(
"### {{TDEF:REWIRING}}. Pathway-rewiring summary (LUAD top pathways; BRCA permutation statistics in footnotes).",
"### {{TDEF:REWIRING}}. Framework validation of patient-specific pathway rewiring in LUAD and BRCA."
)

# A8 methods 2.7
rep(
"Between-stratum rewiring was tested per pathway with a two-sample z-statistic on the per-edge mean weights using a pooled standard error, and the false discovery rate was controlled with the Benjamini–Hochberg procedure over the K pathways; the label-permutation null was generated with 1,000 permutations of the event labels. Pathway-level enrichment of the top-20 rewired pathways against a curated LUAD driver-pathway list was tested with the hypergeometric distribution over the 57-pathway cancer-core catalogue. For each trained model, per-patient edge weights were extracted from the last adaptive layer and patients were split at the median predicted risk. Static-model and standard-GAT controls followed the same protocol, and the permutation P was computed as one plus the number of null permutations with at least as many significant pathways, divided by 1,001.",
"Per-patient edge weights were extracted from the last adaptive layer and patients were split at the median predicted risk. Between-stratum rewiring was tested per pathway on the per-sample mean edge weight within each pathway, reporting Cohen's d with a normal-approximation 95% CI, and the false discovery rate was controlled with the Benjamini–Hochberg procedure. Each pathway was additionally tested under 1,000 within-pathway label permutations of the risk strata; the permutation P was one plus the number of null permutations with at least as large an absolute effect, divided by 1,001. At the cohort level, the number of significant pathways was compared with a 1,000-permutation null obtained by permuting the risk labels, with the permutation P computed as one plus the number of null counts at least as large as the observed count, divided by 1,001. Two matched random gene-set controls assessed pathway-identity selectivity: for each real pathway, 200 random gene sets of equal size with matched internal edge counts, and 200 random equal-size subsets drawn from real pathway blocks so that size and density were matched, were scored with the identical effect-size statistic, and the percentile of each real pathway within its null distribution was recorded. Pathway-level enrichment of the top-20 pathways ranked by permutation P against a curated LUAD driver-pathway list was tested with the hypergeometric distribution over the 57-pathway cancer-core catalogue. Static-model, randomized-partition and standard-GAT controls followed the same protocol. All analyses are implemented in benchmark/rewiring_analysis.py and the work/ scripts of the repository."
)

io.open(P, "w", encoding="utf-8", newline="\n").write(t)
print("TEMPLATE OK, length", len(t))
