# -*- coding: utf-8 -*-
"""Part B: discussion + end sections."""

DISCUSSION = """## 4. Discussion

The conceptual contribution of this work is a framework rather than a module tweak. Existing pathway GNNs, including PathGNN [pathgnn2022], Cox-Path [coxpath2024], prior-knowledge-guided multilevel GNNs [priorgnn2024], and the multi-omics PathMoG [pathmog2026], treat the pathway graph as a fixed patient-invariant prior and stop at the risk score. We instead treat the effective graph as a per-patient object and provide the statistical machinery to interrogate its rewiring: edge-level and pathway-level tests with BH-FDR control [bh1995], label-permutation nulls, a static-model negative control, a standard-GAT architectural control, and clinical anchoring. The discrimination of the adaptive model was comparable to deep survival baselines, and we make no claim that per-patient attention improves the C-index; its distinguishing value is that the learned patient-specific edge weights can be formally tested, are clinically anchored to Ki-67 and TMB [tmb2017], and are absent in static models by construction. The pathway partition is an interpretive labeling of these differences rather than a statistical necessity, as detailed in Section 3.4.2.

**Comparison with PathMoG.** PathMoG is the closest recent work; it also organizes genes into KEGG pathway modules and uses hierarchical attention for multi-omics survival prediction [pathmog2026]. The two frameworks are complementary in scope and differ in three substantive ways. First, the topology is static in PathMoG and adaptive in Path-AGNN-Cox: PathMoG precomputes patient-invariant pathway topologies and learns attention within them, whereas Path-AGNN-Cox additionally learns the graph temperature per patient, and its rewiring analysis directly interrogates patient-specific graph dynamics. Second, the omics scope differs: PathMoG requires mutation and CNV in addition to expression, which limits its applicability to the many clinical cohorts that only measure transcriptomes; Path-AGNN-Cox is a single-transcriptome model that is immediately applicable to the large body of GEO microarray cohorts, as supported by our {{N_EXTERNAL}}-cohort external validation. Third, the external validation breadth differs: PathMoG validated transferability in a single breast-cancer cohort, METABRIC [metabric2012]; Path-AGNN-Cox was validated in {{N_EXTERNAL}} GEO cohorts spanning {{N_DATASETS}} tumor types. These differences position Path-AGNN-Cox as a lightweight, broadly deployable alternative for single-omics clinical and public cohorts, while PathMoG remains the reference for multi-omics integration.

**Limitations.** First, the predictive performance of the adaptive model did not exceed penalized Cox baselines on internal CV, and ablations did not isolate a significant C-index contribution from the adaptive gate, the pathway constraint, or the regularization terms; interpretability is the rationale for its use rather than a discrimination gain. Second, the learnable malignancy gate converged to values near zero in the trained models, so the effective sample-specificity arises from the attention coefficients themselves; we therefore describe the mechanism as patient-specific attention rather than as demonstrable malignancy-driven gating. Third, hypergeometric enrichment of the top-20 rewired pathways ranked by permutation P against a curated LUAD driver-pathway list was not significant ({{ENRICH_LUAD_HITS}} hits, {{ENRICH_LUAD_P}}); an equivalent test was not performed for BRCA because no matched curated driver-pathway list was available. Fourth, matched random gene-set controls were cohort-dependent: real pathways were enriched above matched random sets in BRCA and KIRC beyond a simulated pure-null baseline of the statistic, whereas LUAD showed no enrichment beyond the structural null; the pathways that exceeded both permutation and matched-set nulls remain hypothesis-generating, and the pathway prior is retained as an interpretable organizing principle rather than as evidence of specific pathway activation. Fifth, attention weights provide hypothesis-generating rather than causal evidence, and all cohorts are retrospective; prospective validation is required. Sixth, the pan-cancer benchmark used a single seed; a three-seed sensitivity analysis on LUAD, BRCA and KIRC, the cohorts used for the rewiring analyses, showed stable C-index values of {{SEEDS_LUAD}} in LUAD, {{SEEDS_BRCA}} in BRCA and {{SEEDS_KIRC}} in KIRC, but seed variance was not propagated to all cohorts. Seventh, the two LUAD pathways that were significant in the training cohort were not replicated at the pathway level across three independent external LUAD cohorts; DNA replication showed a Stouffer z of {{EXT_META_DNA_Z}} with {{EXT_META_DNA_P}} and {{EXT_META_DNA_DIR}} of {{EXT_META_N_COHORTS}} cohorts in the same direction, and homologous recombination a z of {{EXT_META_HR_Z}} with {{EXT_META_HR_P}} and {{EXT_META_HR_DIR}} of {{EXT_META_N_COHORTS}}; pathway-level rewiring findings should therefore be interpreted within the cohort in which they were derived. Eighth, the direction of the pathway-specific rewiring effects was systematically opposite between BRCA and KIRC, consistent with the sign symmetry of the attention mechanism; absolute attention directions are therefore not compared across cohorts, and only the within-cohort existence of risk-associated pathway structure is claimed.

---
"""

END_SECTIONS = """## Author contributions

Zhipeng Wang: conceptualization, methodology, software, formal analysis, and writing of the original draft. Luning Wang: data curation, methodology, and writing of the original draft. Changsong Wang: supervision, project administration, and review and editing of the manuscript. Pengli Zhai: resources and review and editing of the manuscript. Zejun Liu: validation and review and editing of the manuscript. Hui Feng: investigation and visualization. Hongmei Liu: data curation and validation. Qian Hou: software and visualization. Ming Guo: formal analysis and review and editing of the manuscript.

## Ethics approval

This study was approved by the Ethics Committee of Zhongda Hospital Affiliated with Southeast University. All analyses used publicly available de-identified data; no new clinical data or patient samples were collected.

## Data availability

All data were obtained from public repositories: TCGA RNA-seq and clinical annotations from UCSC Xena [xena2020] and GDC, GEO series matrices and platform annotations from NCBI GEO [geo2013,geoquery2007], and IMvigor210 data from the original publication [imvigor2018]. Accession numbers are listed in Table 1. To protect patient privacy, per-patient expression matrices, clinical records, and per-patient model outputs are not redistributed; aggregate results required to reproduce every table and figure are provided in the repository.

## Competing interests

The authors declare no competing interests.

---
"""
